name: umiuni2d_flutter
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0
  umiuni2d:
    path: ../engine_core
  umiuni2d_platform_path:
    git: https://github.com/kyorohiro/umiuni2d_platform_path.git
  umiuni2d_audio:
    git:
      url: https://github.com/kyorohiro/umiuni2d_audio.git
      ref: v0.0.1

flutter:
  uses-material-design: true
